#!/usr/bin/env bash
set -eu
# example use case: ./start-k8s production
# Set the environment variable to the first command-line argument or default to 'staging'
ENV=${1:-staging}
if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
    echo "Error: env must be either 'staging' or 'production'"
    exit 1
fi

# Make the script itself executable
chmod +x "$0"

kubectl delete -k k8s/overlays/$ENV
kubectl  delete ns beebop