#!/usr/bin/env bash
set -eu
# assume already athenticated to vault
ENV=${1:-staging}
if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
    echo "Error: env must be either 'staging' or 'production'"
    exit 1
fi
DEST=${PWD}/k8s/ssl
mkdir -p $DEST 

kubectl -n beebop create secret tls tls-secret \
    --cert <(vault read -field=cert /secret/beebop/ssl/$ENV) \
    --key <(vault read -field=key /secret/beebop/ssl/$ENV)