#!/usr/bin/env bash
set -eu

ENV=${1:-staging}
if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
    echo "Error: env must be either 'staging' or 'production'"
    exit 1
fi
# assume already athenticated to vault

GOOGLE_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/$ENV/google)
GOOGLE_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/$ENV/google)
GITHUB_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/$ENV/github)
GITHUB_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/$ENV/github)
SESSION_SECRET=$(vault read -field=secret /secret/beebop/express-session)

kubectl -n beebop create secret generic auth-secrets \
  --from-literal=googleClientId="$GOOGLE_CLIENT_ID" \
  --from-literal=googleClientSecret="$GOOGLE_CLIENT_SECRET" \
  --from-literal=githubClientId="$GITHUB_CLIENT_ID" \
  --from-literal=githubClientSecret="$GITHUB_CLIENT_SECRET" \
  --from-literal=sessionSecret="$SESSION_SECRET"