apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: beebop

namespace: beebop # assume this namespace exists

resources:
  - persistence.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
