apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beebop-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # todo: storage capacity as per requirements
      storage: 50Gi
