apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - count: 2
    name: beebop-deploy-py-worker

labels:
  - includeSelectors: true
    pairs:
      env: staging
patches:
  - path: ingress-patch.yaml
